kind: PersistentVolume
apiVersion: v1
metadata:
  name: ora-data-claim
spec:
  storageClassName: slow
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
      path: /home/ora
